version: "2"

services:
  mongo: 
    image: mongo:latest
    volumes: 
    - mongodata:/data/db
    ports: 
    - "27017:27017"
    container_name: mongo
  mage:
    build: .
    image: mage:latest
    links:
    - mongo
    ports:
    - "4242:4242"
    depends_on:
    - "migrator"
    container_name: mage
  migrator:
    image: mage:latest
    links:
    - mongo
    command: npm run migrate
    depends_on:
    - "mongo"
    container_name: migrator
volumes:
  mongodata:
